default: main

main: main.cpp account.cpp checking.cpp creditcard.cpp savings.cpp account.hpp checking.hpp creditcard.hpp savings.hpp
	g++ -o main main.cpp account.cpp checking.cpp creditcard.cpp savings.cpp account.hpp checking.hpp creditcard.hpp savings.hpp

clean:
	rm -f main.o main
